import React from 'react';
import { Cpu, Code2, Cloud, Sparkles } from 'lucide-react';

const TrackCard: React.FC<{ icon: React.ReactNode; title: string; desc: string }> = ({ icon, title, desc }) => (
    <div className="p-6 rounded-2xl bg-white/5 border border-white/5 hover:border-tech-blue/30 transition-colors group">
        <div className="w-12 h-12 rounded-lg bg-deep-space border border-white/10 flex items-center justify-center mb-4 text-tech-gold group-hover:text-tech-blue group-hover:scale-110 transition-all">
            {icon}
        </div>
        <h3 className="text-xl font-bold text-white mb-2">{title}</h3>
        <p className="text-slate-400 text-sm leading-relaxed">{desc}</p>
    </div>
);

export const Tracks: React.FC = () => {
    return (
        <section className="bg-deep-space py-20 px-4 relative border-t border-white/5">
             <div className="max-w-6xl mx-auto">
                <div className="text-center mb-16">
                    <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">Speaker Tracks</h2>
                    <p className="text-slate-400 max-w-2xl mx-auto">We are looking for engaging sessions that blend technical depth with the festive spirit of the season. Whether it's strict "Model Context Protocol" or joyful "Merry Christmas People" vibes, we want it all.</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                    <TrackCard 
                        icon={<Cpu />}
                        title="Generative AI & LLMs"
                        desc="Dive deep into the latest models, RAG architectures, and agentic workflows."
                    />
                    <TrackCard 
                        icon={<Cloud />}
                        title="Data Engineering"
                        desc="Modern data stacks, pipelines, and infrastructure scaling for AI workloads."
                    />
                     <TrackCard 
                        icon={<Code2 />}
                        title="AI Software Dev"
                        desc="Building apps with Copilots, coding assistants, and integrating AI APIs."
                    />
                     <TrackCard 
                        icon={<Sparkles />}
                        title="Creative AI"
                        desc="Art, music, and festive fun generated by AI. The lighter side of tech."
                    />
                </div>
             </div>
        </section>
    );
};